Feature/new angular theorie
it-ninjas/labs pull request #66
Opened 2023-05-30 07:53 UTC by cedi-sbb

2023-05-30 08:43 UTC, cedi-sbb commented
Muss noch die Ziele bei den Themen ergänzen

2023-06-01 07:20 UTC, LFR3052 requested changes
man, man, man...

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/04_6_ts_internationalization.md
> +2. Inhalt einfügen: Nun kann man die Wörter und Texte, die man dynamisch übersetzen, lassen möchte in die JSON-Dateien eintragen. Diese werden nach dem Key-Value Prinzip eingetragen, wobei der Key in
```suggestion
2. Inhalt einfügen: Nun kann man die Wörter und Texte, die man dynamisch übersetzen, lassen möchte in die JSON-Dateien eintragen. Diese werden nach dem Key-Value Prinzip eingetragen, wobei der Key in Capslock ist. Zudem müssen die Keys in allen JSONs immer gleich sein für den gleichen Text, ansonsten funktionierts nicht. Man kann einem Key auch mehrere weitere Key-Value Paare geben, dies wird getan, wenn sie zueinander gehören. 
```

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/08_5_ts_ngrx-example.md
> +Als kleines Beispiel, wie man NgRx verwendet, setze man eine kleines neues Angular-projekt auf und schreibt eine Anwendung mit einem Counter welchen man Inkrementieren, Dekrementieren und Resetten ka
```suggestion
Als kleines Beispiel, wie man NgRx verwendet, setze man ein kleines neues Angular-projekt auf und schreibt eine Anwendung mit einem Counter welchen man Inkrementieren, Dekrementieren und Resetten kann.
```

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/08_5_ts_ngrx-example.md
> +Danach NgRx [installieren](./08_1_ts_ngrx#installation)
```suggestion
Danach NgRx [installieren](./08_1_ts_ngrx#installation).
```

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/08_5_ts_ngrx-example.md
> +Nun erstellt man der Übersicht halber noch zwei Ordner, einer names actions und der ander names reducers. Darin werden dann alle Actions und reducer erstellt.
```suggestion
Nun erstellt man der Übersicht halber noch zwei Ordner names actions und reducers. Darin werden dann alle Actions und Reducer erstellt.
```

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/08_5_ts_ngrx-example.md
> +---
Ist das nicht eher schon ein Lab?

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/08_5_ts_ngrx-example.md
> +## im AppComponent anzeigen
```suggestion
## Im AppComponent anzeigen 
```

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/09_1_einfuehrung_jwt.md
>  title: "Json Web Token Authorisation (JWT)"
Eventuell rename der Dateu zu Exkurs_JWT?

2023-06-01 07:20 UTC, LFR3052 commented on content/en/docs/web/angular/images/angular-stylesheet.png
Wäre eventuell schlau, wenn hier im Screenshot SCSS ausgewählt ist?

2023-06-01 07:20 UTC, LFR3052 requested changes
man, man, man...

2023-06-01 14:31 UTC, otifant reviewed
Hier mal ein paar Kommentare von mir :)

2023-06-01 14:31 UTC, otifant commented on content/en/docs/web/angular/03_13_ts_dependency_injection.md
> + Was eine Dependency Injection genau ist und wozu man diese verwendet kann man hier nachlesen.
Ich weiss, ein bisschen lange, aber bei diesem Thema würde ich es von Anfang an einfach machen, weil man sonst mega lange verwirrt ist, wenn man von diesem Thema hört.

```suggestion
 Um eine loose Kopplung zu erreichen, werden verschiedene Aufgaben wie das Laden von Server-Daten in verschiedene Dateien ausgelagert. Die einzelnen Klassen haben Abhängigkeiten zu einander. In Angular gibt man die Abhängigkeiten zu anderen Klassen oft z.B. im Konstruktor an.
 
Angular erstellt und übergibt dann automatisch Instanzen dieser Klassen beim Laden der entsprechenden Klasse.

Auf diese Weise werden die Klassen wiederverwendbarer und einfacher testbar.
```

2023-06-01 14:31 UTC, otifant commented on content/en/docs/web/angular/03_12_ts_interceptors.md
> +    Was Interceptors genau sind kann in diesem Kapitel nachgelesen werden.
```suggestion
    Manipuliere alle HTTP-Anfragen an einer zentralen Stelle und erstelle ein Default-Exception-Handling für alle gescheiterten HTTP-Anfragen.
```

2023-06-06 04:23 UTC, merged