Feature/angular base reafctoring
it-ninjas/labs pull request #67
Opened 2023-06-06 04:25 UTC by cedi-sbb

2023-06-12 16:48 UTC, otifant commented on content/en/solutions/web/typescript/solution 1/tsconfig.json
> +    "solution 1/src/**/*.ts"
Diese Datei lässt den Build failen... Ich weiss nicht was der Check genau macht, aber für mich macht dieses `tsconfig.json` so mehr Sinn:

```suggestion
    "./src/**/*.ts"
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/typescript/_index.md
> +weight: 1
Achtung: nun kommt TypeScript noch vor IDE und HTML und CSS!

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/typescript/_index.md
> +title: "Typescript"
```suggestion
title: "TypeScript"
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/typescript/_index.md
> +    Typescript lernen
Bitte etwas motivierenderes ;)
```suggestion
    Typisierte Webprogrammierung.
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/03_linter.md
> +weight: 1
```suggestion
weight: 3
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/03_linter.md
> +"editor.formatOnSave": true,
Ist dieses `formatOnSave` wirklich für ESLint? Das ist doch für den Auto-Formatter?

Wenn du diesen Wert auf `true` setzt, dann kannst auch gleich spezifizieren, mit was (würde ich, damit man das nicht für jeden Dateityp zuerst den Formatter auswählen muss, damit es funktioniert):

```suggestion
"editor.formatOnSave": true,
"editor.defaultFormatter": "esbenp.prettier-vscode",
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/03_linter.md
> +  "tabWidth": 2
Würde vielleicht gerade ein umfangreicheres Beispiel zeigen, damit man sieht, was alles so möglich ist ;)
```suggestion
  "printWidth": 120,
  "singleQuote": true,
  "useTabs": false,
  "tabWidth": 2,
  "semi": true,
  "bracketSpacing": true
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/02_nodejs.md
> +weight: 1
```suggestion
weight: 2
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/04_ide_and_tools_selftesting.md
> +weight: 1
```suggestion
weight: 4
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/01_ide.md
> +    VS-Code:
Würde ich in die entsprechenden Kapitel für die IDE verschieben

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/01_ide.md
> +Standardmässig blockiert der Webbrowser das Laden von JavaScript-Modulen vom lokalen Dateisystem aus Sicherheitsgründen. Dies wird als "Same-Origin Policy" bezeichnet und dient dazu, das Ausführen po
Zu diesem Zeitpunkt hat man noch kaum Knowhow von Web. Mach es nicht kompliziert!

Ich würde irgendwie in diese Richtung gehen (vielleicht noch ein bisschen vereinfachen):

```suggestion
Normalerweise verwendet der Browser HTTP, um Websites und andere Ressourcen von einem Server zu laden. Beim lokalen Entwickeln greifen Entwickler jedoch häufig direkt über den Browser auf das Dateisystem zu. Es gibt jedoch bestimmte Techniken, wie z. B. JavaScript-Module, die Ressourcen nur über HTTP laden können. Aus diesem Grund müssen wir für bestimmte Funktionen auch lokal einen Webserver verwenden, der die Ressourcen über HTTP bereitstellt.

Die Live-Server-Erweiterung erfüllt genau diese Anforderungen: Sie ermöglicht es, Dateien in einem bestimmten Ordner (dem Projektverzeichnis) auf deiner Festplatte über HTTP verfügbar zu machen. Ein zusätzliches Feature besteht darin, dass deine Seite automatisch aktualisiert wird, sobald du Änderungen vornimmst.
```

2023-06-12 16:48 UTC, otifant commented on content/en/docs/web/ide/01_ide.md
> +Die Live-Server Extension ist eine beliebte Erweiterung für Visual Studio Code, die Entwicklern dabei hilft, Webanwendungen während der Entwicklung automatisch neu zu laden. Sie ermöglicht es, eine l
Wie brauchst du einen solchen in IntelliJ?

2023-06-13 12:07 UTC, otifant reviewed
Sehr cool, was du alles dokumentieren konntest. Merci hierfür 💪

Im Moment habe ich vor allem Bedenken, dass die Theorie nun sehr viel theoretischer wurde und man nicht mehr wirklich mitcoden kann bei Angular.

Bevor ich diese neue Version veröffentlichen würde, sollte es noch mehr Übungsgelegenheiten direkt in den Docs verlinkt haben. Sonst denke ich, dass es viel zu schnell ablöscht, weil sehr theoretisch...

2023-06-13 12:07 UTC, otifant commented on content/en/labs/web/_index.md
> +weight: 1
Achtung: Nun kommen die Web-Labs vor denjenigen von Java!

2023-07-27 06:31 UTC, LFR3052 requested changes
Noch einige Fehler in der Rechtschreibung. Inhalt insgesamt gut, noch kleinere Anpassungen nötig.

2023-07-27 06:31 UTC, LFR3052 requested changes
Noch einige Fehler in der Rechtschreibung. Inhalt insgesamt gut, noch kleinere Anpassungen nötig.

2023-08-07 13:12 UTC, LFR3052 approved these changes

2023-08-08 15:58 UTC, merged