Überarbeitung #J1
it-ninjas/labs pull request #71
Opened 2023-07-27 12:31 UTC by otifant

2023-08-02 06:42 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/06_strings.md
> +String name = "Kermit the Frog";
```suggestion
String name = "It-Ninja";
```
Eventuell ein Ninja bezogener Name? Kann gerne auch etwas Kreativeres sein als `It-Ninja`

2023-08-02 06:42 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/06_strings.md
> +In diesem Fall gibt die Methode `7` zurück, weil das `@` an der 8. Stelle sich befindet.
```suggestion
In diesem Fall gibt die Methode `7` zurück, weil sich das `@` an der 8. Stelle befindet.
```

2023-08-02 06:42 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/06_strings.md
> +In diesem Beispiel interessiert und die Information nach dem ":", welches sich immer an 6. Stelle befindet:
```suggestion
In diesem Beispiel interessiert uns die Information nach dem ":", welches sich immer an 6. Stelle befindet:
```

2023-08-02 06:42 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/07_arrays.md
> +Häufig benötigen Software-Entwickler mehrere zusammengehörige Variablen desselben Datentyps, die logisch oder verwaltungstechnisch zusammengehören. Es wäre aber sehr aufwendig, diese Variablen alle e
```suggestion
Häufig benötigen Software-Entwickler mehrere zusammengehörige Variablen desselben Datentyps, die logisch oder verwaltungstechnisch zusammengehören. Es wäre aber sehr aufwendig, diese Variablen alle einzeln zu deklarieren und zu verarbeiten. Zudem ist es möglich, dass die Anzahl an Objekten noch unbekannt ist und erst bei der Ausführung des Programms definiert wird. Deswegen wird in Java, wie in anderen Programmiersprachen auch, die Verwendung von Arrays unterstützt. In Arrays lassen sich beliebige primitive Datentypen und Objekte speichern und systematisch bearbeiten. Alle Variablen haben einen gemeinsamen Namen, werden aber über unterschiedliche Indizes angesprochen.
```

2023-08-02 06:42 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/09_static-non_static.md
> +Will man hingegen den Namen eines der Studenten holen, so erfolgt der Zugriff über die Instanz des entsprechenden Objektes.
```suggestion
Will man hingegen den Namen einer der Studenten holen, so erfolgt der Zugriff über die Instanz des entsprechenden Objektes.
```

2023-08-04 07:35 UTC, otifant commented on content/en/docs/java/java-grundlagen/01_java_intro.md
> +* Ich weiss, dass geschweifte Klammern einen Block definieren und ich verwende sie in jeder Kontrollstruktur, um die Code-Blocks voneinander abzugrenzen (lieber zu viel klammern als zu wenig).
☑️ Erledigt

2023-08-04 11:20 UTC, otifant commented on content/en/docs/java/java-grundlagen/01_java_intro.md
> +Gegenwärtig erscheinen im Halbjahrestakt neue Java-Versionen; die neuste Version, Java 17, wurde im September 2022 veröffentlicht.
Habe folgendes stattdessen geschrieben: `die nächste Version, Java 21, wird im September 2023 veröffentlicht.`

2023-08-04 11:22 UTC, otifant commented on content/en/docs/java/java-grundlagen/01_java_intro.md
> +Der Compiler wandelt den Quellcode in Bytecode um (Kompilat) und anschliessend führt die Java Virtual Machine (JVM) den Bytecode aus.
☑️ Erledigt

2023-08-04 11:23 UTC, otifant commented on content/en/docs/java/java-grundlagen/01_java_intro.md
> +---
Nein.

2023-08-04 11:28 UTC, otifant commented on content/en/docs/java/java-grundlagen/04_primitive_types.md
> +Trotz Nachkommastellen dürfen Fliesskommzahlen des Typs `float` niemals zur Berechnung von Währungen verwendet werden. Innerhalb von Java wird ein float stets als Dezimalbruch geführt und die Ungenau
Habe es so umformuliert:

`Ungenauigkeit ist der Grund, warum der Datentyp float NICHT für Währungsrechnungen verwendet werden soll.`

2023-08-04 11:30 UTC, otifant commented on content/en/docs/java/java-grundlagen/04_primitive_types.md
> +| Wir können ein Char-Literal als Integral-Literal angeben, das den Unicode-Wert des Zeichens darstellt, und Integral-Literale können entweder in Dezimal-, Oktal- oder Hexadezimalform angegeben werde
☑️  erledigt

2023-08-04 11:31 UTC, otifant commented on content/en/docs/java/java-grundlagen/05_reference_types.md
> +Nebst primitiven Datentypen gibt es Referenzdatentypen. Eine Variable diesen Typs enthält nicht die Werte selbst wie eine Variable primitiven Typs, sondern nur einen Verweis (Referenz) auf den Speich
Habe es so umformuliert: 

`Eine Variable von diesem Typ`

2023-08-04 11:33 UTC, otifant commented on content/en/docs/java/java-grundlagen/06_strings.md
> +Oft generierst du aus verschiedenen Variablen EIN neuer `String`. Angenommen du hast eine Variable für "name" und "age" (Alter), dann kannst du wie folgt den String "Hallo {name}, du bist {age} Jahre
☑️ erledigt

2023-08-04 11:40 UTC, otifant commented on content/en/docs/java/java-grundlagen/06_strings.md
> +String name = "Kermit the Frog";
Habe mal den Ninja Turtle Leonardo genommen.

2023-08-04 11:41 UTC, otifant commented on content/en/docs/java/java-grundlagen/06_strings.md
> +In diesem Fall gibt die Methode `7` zurück, weil das `@` an der 8. Stelle sich befindet.
☑️ erledigt

2023-08-04 11:42 UTC, otifant commented on content/en/docs/java/java-grundlagen/06_strings.md
> +In diesem Beispiel interessiert und die Information nach dem ":", welches sich immer an 6. Stelle befindet:
☑️ erledigt

2023-08-04 11:44 UTC, otifant commented on content/en/docs/java/java-grundlagen/07_arrays.md
> +Häufig benötigen Software-Entwickler mehrere zusammengehörige Variablen desselben Datentyps, die logisch oder verwaltungstechnisch zusammengehören. Es wäre aber sehr aufwendig, diese Variablen alle e
☑️ erledigt

2023-08-04 11:46 UTC, otifant commented on content/en/docs/java/java-grundlagen/09_static-non_static.md
> +Will man hingegen den Namen eines der Studenten holen, so erfolgt der Zugriff über die Instanz des entsprechenden Objektes.
Habe es wie folgt geändert: `von einem`

2023-08-04 13:57 UTC, LFR3052 requested changes
Noch eine kleine Änderung :)

2023-08-04 13:57 UTC, LFR3052 commented on content/en/docs/java/java-grundlagen/_index.md
> +Hiermit beginnt deine Reise ~~nach~~ mit Java!
```suggestion
Hiermit beginnt deine Reise mit Java!
```

2023-08-04 14:20 UTC, LFR3052 approved these changes

2023-08-04 14:20 UTC, merged