Feature/j2 refactoring
it-ninjas/labs pull request #77
Opened 2023-08-15 15:54 UTC by otifant

Habe das #J2 noch ein bisschen überarbeitet:

* Module noch neu angeordnet
* List, Streams und Generics sind nun auch im J2 drin in den Docs
* Streams-Theorie ergänzt
* 1 neues Stream-Lab
* Stream-Exam wurde ausgetauscht mit Soccer Championship

2023-09-21 03:25 UTC, ksmadar commented on content/en/exams/java/java-oop/results.txt
Die Formatierung der Datei ist nicht optimal. Es werden TABs und Spaces verwendet, sodass die Zeilen sind z.T. verschoben. Evtl. nur mit Spaces formatieren oder eine md-Datei mit einer Tabelle statt eine txt-Datei verwenden.

2023-09-21 03:28 UTC, ksmadar commented on content/en/exams/java/java-oop/OOPExam.md
> +* Jedes Spiel beschreibt entweder eine Vorrunde/Gruppenspiel (GROUP), Play-Off, Viertel- (QUARTER), Halbfinale (SEMI) oder Finale.
Warum sind die unterschiedliche "Spielarten" mal mit grosse Buchstaben (GROUP, QUARTER, SEMI) und mal normal (Play-off, Finale) geschrieben? Wenn die Idee ist, dass man hierfür ein Enum verwendet, dann auch PLAYOFF und FINALE schreiben.

2023-09-21 03:47 UTC, ksmadar commented on content/en/exams/java/java-oop/OOPExam.md
> +Lade hierfür die Daten aus der <a href="../results.txt" download>`results.txt`</a>-Datei. Du sollst die Daten nicht via Dateisystem laden, sondern du kannst die Informationen aus dieser Datei direkt
Hier ist nicht klar was genau gemeint ist bzw. was ist hier bzgl. der Information im results.txt erwartet wird.

2023-09-21 03:50 UTC, ksmadar commented on content/en/exams/java/java-oop/OOPExam.md
> +* Über die Mannschaften (Team) wissen wir, wie sie heissen (name), z.B. "Schweiz".
Ist die einzige Aufgabe der Klasse "Team", ein Behälter für einen String (name) zu sein? wenn ja, dann braucht es hierfür keine Klasse, höchstens ein Enum wenn man die Teamnamen vordefinieren möchte... Ist es so gemeint?

2023-10-17 12:31 UTC, otifant commented on content/en/docs/java/j2-collection-crash-course/02-streams.md
> +* Ich kann Streams für die Iteration über Listen anwenden.
Was genau ist mit der Stream-API-Dokumentation gemeint und wie (Beispiel) ist dieses Ziel gemeint?

2023-10-17 13:03 UTC, otifant commented on content/en/docs/java/j2-collection-crash-course/02-streams.md
> +### Funktionale Interfaces
Oder ich schmeisse die Functional Interfaces komplett aus dem #J2?

2023-10-24 15:49 UTC, otifant commented on content/en/docs/java/j2-oop/06-initialization-blocks.md
> +**Beispiele**
Habe noch ein Beispiel hinzugefügt. :D

2023-10-31 08:16 UTC, otifant reviewed
Habe nun alles Feedback implementiert.

2023-10-31 08:16 UTC, otifant commented on content/en/exams/java/java-oop/OOPExam.md
> +Lade hierfür die Daten aus der <a href="../results.txt" download>`results.txt`</a>-Datei. Du sollst die Daten nicht via Dateisystem laden, sondern du kannst die Informationen aus dieser Datei direkt
Habe das so umformuliert:

Verwende zur Demonstration die Daten aus der <a href="../results.txt" download>`results.txt`</a>-Datei. Du sollst die Daten nicht automatisiert via Dateisystem laden, sondern du kannst die Informationen aus dieser Datei direkt hartkodiert in eine `.java`-Datei hinein kopieren und in Java-Code umschreiben, damit es mit deinen Klassen kompatibel ist. Damit ist keine Hexerei erwartet, sondern wenn z.B. folgendes in der `results.txt`-Datei steht

```
# Gruppe 1				
Frankreich	    Jugoslawien	        0:1 
```

dann kannst du das wie folgt direkt in deine Java-Datei schreiben:

```java
new Game(FRANCE, YUGOSLAVIA, 0, 1)
```

2023-11-06 11:52 UTC, ksmadar requested changes
Habe das Modul nochmals angeschaut. Ich bin nun überzeugt, dass die Theorie zu den Streams im Collections-Modul wiederhergestellt werden muss und zwar - mind. vorerst - wie sie bis jetzt war. Crash-Course Listen kann ruhig vor OOP sein, aber Streams benötigt mehr Vorwissen, als es vor dem OOP Modul vorhanden ist.

Habe noch ein paar kleine Kommentare/Verbesserungsvorschläge und eine Überarbeitung der Ziele für Generics.

2023-11-06 11:52 UTC, ksmadar commented on content/en/docs/java/j2-oop/08-enums.md
> +![task1](/images/task.png) Jetzt bist du dran. Löse bitte die [Aufgabe](../../../../labs/java/java-oop) in den OOP-Labs.
```suggestion
![task1](/images/task.png) Jetzt bist du dran. Löse bitte die [Aufgaben](../../../../labs/java/java-oop) in den OOP-Labs.
```

2023-11-06 11:52 UTC, ksmadar commented on content/en/docs/java/java-lists-and-streams-basics.md
Hier soll die ursprüngliche Seite bzgl. Streams wieder hergestellt werden

2023-11-14 09:17 UTC, otifant commented on content/en/docs/java/j2-oop/01-oop.md
> +Die Klasse Patient ist nicht unveränderlich, da jedes Feld eines Objekts geändert werden kann.
Das ist völlig korrekt :) 

Ich verschiebe diesen Teil entweder in die "Felder" oder "Konstruktoren", aber wahrscheinlich eher inst erste. Dann ergänze ich das noch mit "wie man unveränderliche Klassen schreiben kann".

2023-11-28 15:25 UTC, otifant commented on content/en/docs/java/j2-oop/01-oop.md
> +Die Klasse Patient ist nicht unveränderlich, da jedes Feld eines Objekts geändert werden kann.
Habe nun diesen Teil in ein eigenes Kapitel nach den Enums verschoben.

2023-11-28 15:30 UTC, otifant commented on content/en/docs/java/j2-oop/04-fields.md
> +* Ich kann anhand einer Skizze in eigenen Worten den Unterschied zwischen einer Klasse und deren Instanz nennen.
Gibt es dort schon so ähnlich. Habe es hier entfernt.

2023-11-28 16:26 UTC, otifant commented
Habe nun alle Punkte noch einmal aufgegriffen - Bitte um ein weiteres (hoffentlich letztes) Review.

2023-12-06 09:40 UTC, LFR3052 reviewed
Inhalt sehr gut, nur kleine Anpassungen nötig.

Habe noch gesehen, dass es Merge Konflikte gibt, diese sollten noch gelöst werden.

2023-12-12 11:25 UTC, otifant commented on content/en/docs/java/j2-oop/10-mutable-objects.md
> +Das Problem mit unserem Code ist, dass wir erwarten, dass `Color.RED` dem Wert von `new Color(255, 0, 0)` entspricht, da die statische Variable sogar mit `final` deklariert wurde. Und das würde auch
Habe ein Bild hinzugefügt.

2023-12-12 13:33 UTC, LFR3052 commented on content/en/docs/java/j2-oop/01-list-basics.md
> +Dort wo "E" steht, geht es um einen generischen Typ, welcher stellvertretend für einen konkreten Objekttyp steht (Generics werden in einem separaten Modul behandelt).
```suggestion
Der Rückgabetyp "E" seht hier für einen generischen (universellen) Typ, der stellvertretend für einen spezifischen Objekttyp steht. Dieses Vorgehen wird genauer im Modul "Generics" behandelt.
```

2023-12-14 14:55 UTC, marcsprg commented on content/en/docs/java/j2-oop/04-access-modifier.md
> +c.getName();
"p" anstatt ein "c"

2023-12-15 07:47 UTC, otifant commented on content/en/docs/java/j2-oop/04-access-modifier.md
> +c.getName();
```suggestion
p.getName();
```

2023-12-15 07:48 UTC, otifant commented on content/en/docs/java/j2-oop/04-access-modifier.md
> +c.getName();
☑️ Done under merci :D

2023-12-15 07:51 UTC, otifant commented on content/en/docs/java/j2-collection-crash-course/02-streams.md
> +#### Unterschied zwischen generischen Streams und IntStreams
Im Collections-Teil schon

2023-12-15 07:52 UTC, otifant commented on content/en/docs/java/j2-collection-crash-course/02-streams.md
> +        Weapon[] weapons = {
Im Collections-Teil dann schon.

2023-12-15 07:52 UTC, otifant commented on content/en/docs/java/j2-collection-crash-course/02-streams.md
> +Und hier ist noch ein Beispiel, wie du Lambda-Ausdrücke zusammen mit einem eigenen `FunctionalInterface` verwenden kannst:
Draussen

2023-12-15 13:45 UTC, merged