Feature/spring lab
it-ninjas/labs pull request #81
Opened 2023-10-03 06:47 UTC by cedi-sbb

2023-11-01 06:53 UTC, LFR3052 requested changes
Allgemeine Bemerkung: Alle Infos sind im Lab. Aus meiner Sicht sollte noch viel in ein Doc geschrieben werden.

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Lombok ist eine Java-Bibliothek, die es Entwicklern ermöglicht, boilerplate Code in ihren Java-Klassen zu reduzieren. Die Annotationen `@Getter` und `@Setter` sind zwei der am häufigsten verwendeten
```suggestion
Die Annotationen `@Getter` und `@Setter` sind zwei der am häufigsten verwendeten Annotationen in Lombok. Sie generieren automatisch Getter- und Setter-Methoden für die Felder einer Klasse. Lombok ist eine Java-Bibliothek, die es Entwicklern ermöglicht, boilerplate Code in ihren Java-Klassen zu reduzieren. 
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Konfiguriere deine Konfigurationsdatei entsprechend deiner Datenbank.
```suggestion
Erstelle deine Konfigurationsdatei entsprechend deiner Datenbank.
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Wenn die Anwendung mit dem Default-Profil gestartet wird, muss sie sich genauso verhalten, wie mit dem "student" Profil.
Würde es Sinn machen den Profil endpoint hier hinzuzufügen oder erst bei Schritt 7?

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +      PreparedStatementSetter preparedStatementSetter = preparedStatement -> {
Kenne den PreparedStatementSetter gar nicht. Können hier nicht normale PreparedStatements verwendet werden?

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +### Mapping
Eventuell ist hier eine Erklärung nötig, was Mapping ist

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +In JDBC, RowMapper sind ein Interface, das verwendet wird, um das Mapping von Zeilen aus dem ResultSet auf Objekte zu ermöglichen. Es wird verwendet, um das Ergebnis jedes Datensatzes aus der Abfrage
```suggestion
In JDBC, ist der RowMapper ein Interface, das verwendet wird, um das Mapping von Zeilen aus dem ResultSet auf Objekte zu ermöglichen. Es wird verwendet, um das Ergebnis jedes Datensatzes aus der Abfrage in ein Objekt umzuwandeln.
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Implementiere die benötigten Mapper und setze sie an den benötigten Orten ei (wähle selbst, ob du es mit einem Mapper oder Extractor machen willst).
```suggestion
Implementiere die benötigten Mapper und setze sie an den benötigten Orten ein (wähle selbst, ob du es mit einem Mapper oder Extractor machen willst).
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Die Datenbank abfragen werden nun nicht mehr mittels Mockdaten erledigt, sondern es werden SQL-Queries benutzt.
Es wurde ja keine Datenbankabfragen gemacht, daher macht dieser Satz nicht wirklich sinn

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Die Daten, welche man von der Datenbank erhält, werden korrekt gemappt für die DAOs.
```suggestion
* Die erhaltenen Daten, aus der Datenbank, werden korrekt für die DAOs gemappt.
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Eine HTTP-Request Datei liegt vor, welche alle öffentliche Schnittstellen-Methoden ausführen kann.
```suggestion
* Eine HTTP-Request Datei liegt vor, welche alle öffentlichen Schnittstellen-Methoden ausführen kann.
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +In der Testkonfiguration (z. B. `application-test.properties`), konfiguriert man H2 als Datenbank für die Integrationstests. Es wird die Verbindungs-URL, den Treiber und die Anmeldeinformationen für
```suggestion
In der Testkonfiguration (z. B. `application-test.properties`), konfiguriert man H2 als Datenbank für die Integrationstests. Es wird die Verbindungs-URL, der Treiber und die Anmeldeinformationen für H2 festgelegt. Diese Datenbank wird in den Tests automatisch erstellt und verwaltet.
```

2023-11-01 06:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Nun erstellt man SQL-Skripte, wie `schema.sql` und `data.sql`, die das Datenbankschema und Testdaten definieren. Diese Skripte werden während der Testausführung automatisch geladen.
```suggestion
Nun werden SQL-Skripte benötigt, die das Datenbankschema und Testdaten definieren. Diese Skripte werden während der Testausführung automatisch geladen.
```

2023-11-03 13:58 UTC, cedi-sbb commented on content/en/labs/java/spring/01_Spring.md
> +* Java 1.7 oder neuer ist installiert.
ab wo denkst du? java 8, 10, 17, 20?

2023-11-03 14:01 UTC, cedi-sbb commented on content/en/labs/java/spring/01_Spring.md
> +Öffne die Seite: https://start.spring.io/ und ersetzte die Angaben zu Group, Artifact (der Name wird sich automatisch ändern) und Description durch passende Werte.
Füge die Abhängigkeit für "Spring Web" hinzu und drücke den "GENERATE" Knopf.

steht doch das man noch web benötigt

2023-11-03 14:04 UTC, cedi-sbb commented on content/en/labs/java/spring/01_Spring.md
> +* Der Stand des Projektes ist im Bitbucket mit dem Tag "INITIAL_MVN_PROJEKT" versehen
Ich würde entweder das mit dem Tag entfernen oder es im GIT Modul hinzufügen. Denke aber das entfernen besser ist, da GIT zu beginn kommt und Tag nicht zu den Basic/Most used gehört aus meiner Sicht.

2023-11-03 14:08 UTC, cedi-sbb commented on content/en/labs/java/spring/01_Spring.md
> +Diese JSON-Objekte stellen sog. "Resource" dar.
@ksmadar & @ClaudioZesiger denke diese Frage geht an jemand von euch.

2023-11-03 14:16 UTC, cedi-sbb commented on content/en/labs/java/spring/01_Spring.md
> +      PreparedStatementSetter preparedStatementSetter = preparedStatement -> {
Müsste man für PreparedStatements nicht jedes mal die Connection mitgeben? Weil dies sehe ich als nicht sehr sinnvoll hier.

2023-11-28 14:03 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Java 1.7 oder neuer ist installiert.
20

2023-12-05 07:53 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +* Der Stand des Projektes ist im Bitbucket mit dem Tag "INITIAL_MVN_PROJEKT" versehen
@cedi-sbb Könntest du diese Anpassung gleich vornehmen?

2023-12-05 08:21 UTC, LFR3052 commented
Ich habe noch ein Paar vergessene Kommentar überarbeitet. Der Stand sollte jetzt gut sein. 
Vor dem Mergen müssen aber wahrscheinlich noch einige Inhalte entfernt werden, da hier noch viele Erklärungen zu finden sind, was nicht wirklich in ein Lab passt. 

Ich würde diese Anpassungen erst vornehmen, wenn die Spring Doku fertig ist.

2023-12-14 08:57 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Die gezeigte Entität wird mit `@Entity` annotiert, damit sie generell als solche erkannt wird. Die Annotation `@Table` verbindet die Entität
In Doc verschieben?

2023-12-14 08:58 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +Die Annotation `@Id` dient der Markierung des Primärschlüssels.
In Doc verschieben?

2023-12-14 09:01 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +### Mapping
In Doc verschieben?

2023-12-14 09:45 UTC, LFR3052 commented on content/en/labs/java/spring/01_Spring.md
> +#### Möglichkeit 1: JPA-Repository mit Spring Data
Placeholder

2023-12-15 06:42 UTC, LFR3052 approved these changes

2023-12-15 06:43 UTC, merged