feature(J3): fix improvements and add new labs
it-ninjas/labs pull request #97
Opened 2024-03-20 13:50 UTC by cedi-sbb

2024-03-21 06:14 UTC, LFR3052 requested changes

2024-03-21 06:14 UTC, LFR3052 commented on content/en/labs/java/java-ood/03_Vehicles.md
> +- Stauraum
Was ist mit Stauraum gemeint? Liter angabe oder was?

2024-03-21 06:48 UTC, cedi-sbb commented on content/en/labs/java/java-ood/03_Vehicles.md
> +- Stauraum
Stauraum im Kofferraum in m^2

2024-03-22 06:31 UTC, LFR3052 approved these changes

2024-03-22 06:32 UTC, merged